### ISSUE TITLE
Demo: how to create example-ready passage and Q for NER

### ISSUE THREAD

**Issue by savasy** [deepset-ai/FARM#370]
**Question**
When I deploy my trained model in docker, I want to delete built-in models  and put my model instead. I can load my QA model using saving the models under saved_model folder and fixing the docker-compose.yml. 
But I do not know how to put example passage and example Question in it.  

**Additional context**
Add any other context or screenshots about the question (optional).

**Comment by Timoeller** [comment]
Hey @savasy thanks for using FARM and also our docker setup. 
To answer your question we need some more context.

Normally the `docker-compose up` command should create a webbased GUI similar to https://demos.deepset.ai/ where you can paste in questions and texts. There you can also link your custom QA model as I assume you did. You can access that GUI by typing http://localhost:3000 in your browser.
Maybe you could paste any error messages coming up when running the docker compose? I suspect that your custom QA model cannot be loaded correctly... e.g. did you train it with FARM?

**Comment by savasy** [comment]
Hi @Timoeller, using "deepset/farm-inference-api:latest" image and following YML config solved my problems

```
version: '3'
services:
  inference-api:
    image: "deepset/farm-inference-api:latest"
    ports:
      - "5000:5000"
    volumes:
        - ../../Desktop/farming/saved_models:/home/user/saved_models
  inference-ui:
    image: "deepset/farm-inference-ui:latest"
    ports:
      - "3000:80"
```
I can see my model 
However, the last problem is that how Can I put example passage and example question in Turkish Language rather than English.
Thank you
